version: '3.9'
services:
  node:
    container_name: qa-sheets-node
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "4000"
    env_file: .env
    ports:
      - "4000:4000"

